- name: verify and correct file permissions
  shell: for FILE_PATH in $(rpm -Va | grep '^.M'); do rpm --setperms $(rpm -qf "${FILE_PATH}"); done
  args:
    executable: /bin/bash
  tags:
    - NIST-800-53
    - NIST-800-53-AC
    - NIST-800-53-AC-6
    - NIST-800-53-CM
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-SI
    - NIST-800-53-SI-7

- name: verify file hashes
  debug:
    msg: "tasks not yet implemented"
  tags:
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-6
    - NIST-800-53-SI
    - NIST-800-53-SI-7

- name: ensure package manager gpg keys are installed
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  when: ansible_distribution == "RedHat"
  with_items:
    - "{{ rpm_keys.rhel }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure package manager gpg keys are installed
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  with_items:
    - "{{ rpm_keys.centos_6 }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure package manager gpg keys are installed
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  with_items:
    - "{{ rpm_keys.centos_7 }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure package manager gpg keys are installed
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version == "27"
  with_items:
    - "{{ rpm_keys.fedora_27 }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure gpgcheck enabled for package manager
  lineinfile:
    path: /etc/yum.conf
    regexp: '^gpgcheck'
    line: 'gpgcheck=1'
    state: present
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure localpkg_gpgcheck enabled for package manager
  lineinfile:
    path: /etc/yum.conf
    regexp: '^localpkg_gpgcheck'
    line: 'localpkg_gpgcheck=1'
    state: present
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure repo_gpgcheck enabled for package manager
  lineinfile:
    path: /etc/yum.conf
    regexp: '^repo_gpgcheck'
    line: 'repo_gpgcheck=1'
    state: present
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure gpgcheck enabled for package manager
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^gpgcheck'
    line: 'gpgcheck=1'
    state: present
  when: ansible_distribution == "Fedora"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: find all yum repositories
  find:
    paths: "/etc/yum.repos.d/"
    patterns: "*.repo"
  register: yum_find
  tags:
    - NIST-800-53
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)
    - NIST-800-53-SI
    - NIST-800-53-SI-7

- name: ensure gpgcheck enabled for package manager
  with_items: "{{ yum_find.files }}"
  replace:
    dest: "{{ item.path }}"
    regexp: 'gpgcheck = 0'
    replace: 'gpgcheck = 1'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)
    - NIST-800-53-SI
    - NIST-800-53-SI-7

- name: ensure clean_requirements_on_remove enabled in package manager
  lineinfile:
    path: /etc/yum.conf
    regexp: '^clean_requirements_on_remove'
    line: 'clean_requirements_on_remove=1'
    state: present
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)
    - NIST-800-53-SI
    - NIST-800-53-SI-7
