- name: verify and correct file permissions with rpm
  shell: for FILE_PATH in $(rpm -Va | grep '^.M'); do rpm --setperms $(rpm -qf "${FILE_PATH}"); done
  args:
    executable: /bin/bash
  tags:
    - NIST-800-53
    - NIST-800-53-AC
    - NIST-800-53-AC-6
    - NIST-800-53-CM
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-SI
    - NIST-800-53-SI-7

- name: verify file hashes with rpm
  debug:
    msg: "tasks not yet implemented"
  tags:
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-6
    - NIST-800-53-SI
    - NIST-800-53-SI-7

- name: ensure red hat gpg key installed
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  when: ansible_distribution == "RedHat"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure centos gpg key installed
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  with_items:
    - RPM-GPG-KEY-CentOS-7
    - RPM-GPG-KEY-CentOS-Debug-7
    - RPM-GPG-KEY-CentOS-Testing-7
    - RPM-GPG-KEY-EPEL-7
  when: ansible_distribution == "CentOS"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure fedora gpg key installed
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  with_items:
    - "RPM-GPG-KEY-fedora-{{ ansible_distribution_major_version }}-primary"
    - "RPM-GPG-KEY-fedora-{{ ansible_distribution_major_version }}-secondary"
  when: ansible_distribution == "Fedora"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure gpgcheck enabled in main yum configuration
  replace:
    dest: /etc/yum.conf
    regexp: 'gpgcheck=0'
    replace: 'gpgcheck=1'
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: ensure gpgcheck enabled in main yum configuration
  replace:
    dest: /etc/dnf/dnf.conf
    regexp: 'gpgcheck=0'
    replace: 'gpgcheck=1'
  when: ansible_distribution == "Fedora"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-SI
    - NIST-800-53-SI-7
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)

- name: find all yum repositories
  find:
    paths: "/etc/yum.repos.d/"
    patterns: "*.repo"
  register: yum_find
  tags:
    - NIST-800-53
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)
    - NIST-800-53-SI
    - NIST-800-53-SI-7

- name: ensure gpgcheck enabled for all yum package repositories
  with_items: "{{ yum_find.files }}"
  replace:
    dest: "{{ item.path }}"
    regexp: 'gpgcheck = 0'
    replace: 'gpgcheck = 1'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - avail-low
    - avail-medium
    - avail-high
    - NIST-800-53
    - NIST-800-53-MA
    - NIST-800-53-MA-1
    - NIST-800-53-MA-1(b)
    - NIST-800-53-SI
    - NIST-800-53-SI-7