- name: install cronie
  pacman:
    name: cronie
    state: installed
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-3
    - NIST-800-53-CM-3(d)
    - NIST-800-53-CM-3(e)
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)

- name: start and enable cronie
  service:
    name: cronie
    state: started
    enabled: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-3
    - NIST-800-53-CM-3(d)
    - NIST-800-53-CM-3(e)
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)

- name: install aide
  pacman:
    name: community/aide
    state: installed
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-3
    - NIST-800-53-CM-3(d)
    - NIST-800-53-CM-3(e)
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
