- name: install aide
  apt:
    name: aide
    state: installed
    update_cache: yes
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-3
    - NIST-800-53-CM-3(d)
    - NIST-800-53-CM-3(e)
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)

