- block:
  - stat:
      path: /etc/yum.repos.d/redhat-rhui.repo
    register: rhui_repo

  - name: install aide
    yum:
      name: aide
      state: present
      disablerepo: '*'
      enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms
    when: rhui_repo.stat.isreg is undefined or rhui_repo.stat.isreg == False
    tags:
      - conf-low
      - conf-medium
      - conf-high
      - int-low
      - int-medium
      - int-high
      - NIST-800-53
      - NIST-800-53-CM
      - NIST-800-53-CM-3
      - NIST-800-53-CM-3(d)
      - NIST-800-53-CM-3(e)
      - NIST-800-53-CM-6
      - NIST-800-53-CM-6(d)
      - NIST-800-53-CM-6(3)

  - name: install aide
    yum:
      name: aide
      state: present
      disablerepo: '*'
      enablerepo: rhui-REGION-rhel-server-releases
    when: rhui_repo.stat.isreg is defined and rhui_repo.stat.isreg == True
    tags:
      - conf-low
      - conf-medium
      - conf-high
      - int-low
      - int-medium
      - int-high
      - NIST-800-53
      - NIST-800-53-CM
      - NIST-800-53-CM-3
      - NIST-800-53-CM-3(d)
      - NIST-800-53-CM-3(e)
      - NIST-800-53-CM-6
      - NIST-800-53-CM-6(d)
      - NIST-800-53-CM-6(3)
  when: ansible_distribution == "RedHat"

- name: install aide
  yum:
    name: aide
    state: present
  when: ansible_distribution == "CentOS"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-3
    - NIST-800-53-CM-3(d)
    - NIST-800-53-CM-3(e)
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)

- name: install aide
  dnf:
    name: aide
    state: installed
  when: ansible_distribution == "Fedora"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-3
    - NIST-800-53-CM-3(d)
    - NIST-800-53-CM-3(e)
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)

- block:
  - name: System Settings | Installing and Maintaining Software | Software Integrity Checking | Red Hat | Obtain custom policy rule sets from /etc/aide.conf
    shell: /bin/grep "^[A-Z]\+" /etc/aide.conf | /bin/cut -f1 -d '=' | /bin/tr -d ' ' | /bin/sort -u
    args:
      executable: /bin/bash
    register: aide_policy_groups
    changed_when: False

  - debug:
      var: aide_policy_groups

  - name: System Settings | Installing and Maintaining Software | Software Integrity Checking | Red Hat | Configure AIDE to Verify Access Control Lists (ACLs)
    aide_ruleset:
      name: "{{ item }} "
      state: present
      options:
      - acl
    with_items:
    - "{{ aide_policy_groups.stdout_lines }}"
    
  - name: System Settings | Installing and Maintaining Software | Software Integrity Checking | Red Hat | Configure AIDE to Verify Extended Attributes
    aide_ruleset:
      name: "{{ item }} "
      state: present
      options:
      - xattrs
    with_items:
    - "{{ aide_policy_groups.stdout_lines }}"

  - name: System Settings | Installing and Maintaining Software | Software Integrity Checking | Red Hat | Configure AIDE to Use FIPS 140-2 for Validating Hashes
    aide_ruleset:
      name: "{{ item }} "
      state: present
      options:
      - sha512
    with_items:
    - "{{ aide_policy_groups.stdout_lines }}"

  - name: System Settings | Installing and Maintaining Software | Software Integrity Checking | Red Hat | Configure AIDE to Use FIPS 140-2 - Remove Forbidden Hashes
    aide_ruleset:
      name: "{{ item }} "
      state: absent
      options:
      - sha1
      - rmd160
      - sha256
      - whirlpool
      - tiger
      - haval
      - gost
    with_items:
    - "{{ aide_policy_groups.stdout_lines }}"

  tags:
  - NIST-800-53-SI-7.1
  - NIST-800-53-SI-7
  - NIST-800-53-SI
  - SRG-OS-000480-GPOS-00227