---

- name: yum install audit
  yum:
    name: audit
    state: installed
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: dnf install audit
  dnf:
    name: audit
    state: installed
  when: ansible_distribution == "Fedora"