---

- name: yum install audit
  yum:
    name: audit
    state: installed
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  tags:
    - NIST-800-53
    - NIST-800-53-AU

- name: dnf install audit
  dnf:
    name: audit
    state: installed
  when: ansible_distribution == "Fedora"
  tags:
    - NIST-800-53
    - NIST-800-53-AU

- name: reset auid variable for RHEL 7 and CentOS 7
  set_fact:
    auid: 1000
  when: (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "7"
  tags:
    - NIST-800-53
    - NIST-800-53-AU