
- import_tasks: software_integrity_checking/redhat.yml
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

- import_tasks: software_integrity_checking/debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "Kali GNU/Linux" or ansible_distribution == "Linux Mint"

- import_tasks: software_integrity_checking/arch.yml
  when: ansible_distribution == "Archlinux"
