
- import_tasks: software_integrity_checking/redhat.yml
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

- import_tasks: software_integrity_checking/debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "Kali GNU/Linux" or ansible_distribution == "Linux Mint"

- import_tasks: software_integrity_checking/arch.yml
  when: ansible_distribution == "Archlinux"

- name: schedule aide
  cron:
    name: aide
    minute: "{{ aide_minute }}"
    hour: "{{ aide_hour }}"
    day: "{{ aide_day_of_month }}"
    weekday: "{{ aide_day_of_week }}"
    month: "{{ aide_month }}"
    cron_file: aide
    user: root
    job: "/usr/sbin/aide --check"
  tags:
    - linux_cross_platform
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - NIST-800-53
    - NIST-800-53-CM
    - NIST-800-53-CM-3
    - NIST-800-53-CM-3(d)
    - NIST-800-53-CM-6
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)