---
- import_tasks: redhat.yml
  when: ansible_distribution == "Fedora" or ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- block:
    # TODO: fix this is shoddy logic, as it will won't work predictably if one kernel is missing audit=1
    - name: check for presence of audit=1 in grub.cfg
      shell: 'grep "^[[:space:]]*linux.*audit=1.*" /boot/grub/grub.cfg'
      register: grep_result
      ignore_errors: yes

    - name: pass audit=1 to kernel in bootloader via regexp replace
      replace:
        path: /boot/grub/grub.cfg
        regexp: '^(\s*linux.*)$'
        replace: '\1 audit=1'
        backup: yes
      when: grep_result.rc != 0
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "Kali GNU/Linux" or ansible_distribution == "Archlinux" or ansible_distribution == "Linux Mint"
  tags:
    - NIST-800-53
    - NIST-800-53-AU
    - NIST-800-53-AU-14
    - NIST-800-53-AU-14(1)
    - NIST-800-53-AU-1
    - NIST-800-53-AU-1(b)
    - NIST-800-53-AU-2(a)
    - NIST-800-53-AU-2(c)
    - NIST-800-53-AU-2(d)
    - NIST-800-53-AU-2
    - NIST-800-53-AU-10
