---
- import_tasks: redhat.yml
  when: ansible_distribution == "Fedora" or ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: pass audit=1 to kernel in bootloader via regexp replace
  replace:
    path: /boot/grub/grub.cfg
    regexp: '^(\s*linux.*)$'
    replace: '\1 audit=1'
    backup: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "Kali GNU/Linux" or ansible_distribution == "Archlinux"